/*
  Warnings:

  - You are about to drop the column `VENDOR_ID` on the `Warranty` table. All the data in the column will be lost.

*/
-- DropForeignKey
ALTER TABLE "Warranty" DROP CONSTRAINT "Warranty_VENDOR_ID_fkey";

-- AlterTable
ALTER TABLE "Warranty" DROP COLUMN "VENDOR_ID",
ALTER COLUMN "WARRANTY_COVERAGE" DROP NOT NULL,
ALTER COLUMN "WARRANTY_TYPE" DROP NOT NULL,
ALTER COLUMN "BRAND_WARRANTY" DROP NOT NULL,
ALTER COLUMN "WARRANTY_CARD_IMAGE_URL" DROP NOT NULL,
ALTER COLUMN "PRODUCT_PURCHASE_DATE" DROP NOT NULL,
ALTER COLUMN "PRODUCT_SERIAL_NUMBER" DROP NOT NULL,
ALTER COLUMN "WARRANTY_START_DATE" DROP NOT NULL,
ALTER COLUMN "BUYERS_EMAIL" DROP NOT NULL,
ALTER COLUMN "BUYERS_NAME" DROP NOT NULL,
ALTER COLUMN "BUYERS_PHONE" DROP NOT NULL,
ALTER COLUMN "VENDOR_WARRANTY_COVERAGE" DROP NOT NULL;
