export const WarrantyEnums = {
    ACTIVE : "ACTIVE",
    EXPIRED : "EXPIRED",
    EXPIRING_SOON: "EXPIRING_SOON",
    ERROR: "ERROR",
    SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
    INSENSITIVE: "INSENSITIVE",

}