// WebSocket Message Types
export const WS_MESSAGE_TYPE = {
  // Connection
  CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED',
  PING: 'PING',
  PONG: 'PONG',
  ERROR: 'ERROR',
  
  // Subscription
  SUBSCRIBE_WARRANTIES: 'SUBSCRIBE_WARRANTIES',
  SUBSCRIBED: 'SUBSCRIBED',
  SUBSCRIBE_VENDORS: 'SUBSCRIBE_VENDORS',
  VENDOR_SUBSCRIBED: 'VENDOR_SUBSCRIBED',
  SUBSCRIBE_DASHBOARD: 'SUBSCRIBE_DASHBOARD',
  DASHBOARD_SUBSCRIBED: 'DASHBOARD_SUBSCRIBED',
  REFRESH_DASHBOARD: 'REFRESH_DASHBOARD',
  
  // Warranty Events
  WARRANTY_CREATED: 'WARRANTY_CREATED',
  YOUR_WARRANTY_CREATED: 'YOUR_WARRANTY_CREATED',
  WARRANTY_UPDATED: 'WARRANTY_UPDATED',
  YOUR_WARRANTY_UPDATED: 'YOUR_WARRANTY_UPDATED',
  WARRANTY_DELETED: 'WARRANTY_DELETED',
  YOUR_WARRANTY_DELETED: 'YOUR_WARRANTY_DELETED',
  WARRANTY_STATUS_CHANGED: 'WARRANTY_STATUS_CHANGED',
  YOUR_WARRANTY_STATUS_CHANGED: 'YOUR_WARRANTY_STATUS_CHANGED',
  
  // Vendor Events
  VENDOR_CREATED: 'VENDOR_CREATED',
  VENDOR_CREATED_BROADCAST: 'VENDOR_CREATED_BROADCAST',
  VENDOR_UPDATED: 'VENDOR_UPDATED',
  VENDOR_UPDATED_BROADCAST: 'VENDOR_UPDATED_BROADCAST',
  VENDOR_DELETED: 'VENDOR_DELETED',
  VENDOR_DELETED_BROADCAST: 'VENDOR_DELETED_BROADCAST',
  VENDOR_SEARCH_RESULTS: 'VENDOR_SEARCH_RESULTS',
  
  // Claim Events
  CLAIM_CREATED: 'CLAIM_CREATED',
  YOUR_CLAIM_CREATED: 'YOUR_CLAIM_CREATED',
  CLAIM_UPDATED: 'CLAIM_UPDATED',
  YOUR_CLAIM_UPDATED: 'YOUR_CLAIM_UPDATED',
  CLAIM_STATUS_UPDATED: 'CLAIM_STATUS_UPDATED',
  YOUR_CLAIM_STATUS_UPDATED: 'YOUR_CLAIM_STATUS_UPDATED',
  CLAIM_DELETED: 'CLAIM_DELETED',
  YOUR_CLAIM_DELETED: 'YOUR_CLAIM_DELETED',
  
  // Dashboard Events
  DASHBOARD_DATA: 'DASHBOARD_DATA',
  DASHBOARD_UPDATED: 'DASHBOARD_UPDATED',
  DASHBOARD_STATS_UPDATE: 'DASHBOARD_STATS_UPDATE',
  DASHBOARD_ERROR: 'DASHBOARD_ERROR',
};

// WebSocket Ready States
export const WS_READY_STATE = {
  CONNECTING: 0,
  OPEN: 1,
  CLOSING: 2,
  CLOSED: 3,
};

// Warranty Status
export const WARRANTY_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRING_SOON: 'EXPIRING_SOON',
  EXPIRED: 'EXPIRED',
};

// Claim Status
export const CLAIM_STATUS = {
  SUBMITTED: 'SUBMITTED',
  IN_REVIEW: 'IN_REVIEW',
  TECHNICIAN_ASSIGNED: 'TECHNICIAN_ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

// Warranty Categories (for dashboard)
export const WARRANTY_CATEGORY = {
  IN_WARRANTY: 'inWarranty',
  EXPIRING_SOON: 'expiringSoon',
  EXPIRED: 'expired',
};