-- CreateTable
CREATE TABLE "Claim" (
    "CLAIM_ID" TEXT NOT NULL,
    "PRODUCT_ID" TEXT NOT NULL,
    "CLAIM_ISSUE" TEXT NOT NULL,
    "CLAIM_IMAGE_URL" TEXT NOT NULL,
    "SERVICE_DATE" TEXT NOT NULL,
    "SERVICE_TIME" TEXT NOT NULL,
    "CLAIM_ADDRESS" TEXT NOT NULL,

    CONSTRAINT "Claim_pkey" PRIMARY KEY ("CLAIM_ID")
);

-- AddForeignKey
ALTER TABLE "Claim" ADD CONSTRAINT "Claim_PRODUCT_ID_fkey" FOREIGN KEY ("PRODUCT_ID") REFERENCES "Product"("PRODUCT_ID") ON DELETE CASCADE ON UPDATE CASCADE;
