-- CreateTable
CREATE TABLE "Log" (
    "WARRANTY_ID" TEXT NOT NULL,
    "USER_ID" TEXT,
    "MESSAGE" TEXT NOT NULL,
    "STACK" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Log_pkey" PRIMARY KEY ("WARRANTY_ID")
);
