-- CreateTable
CREATE TABLE "User" (
    "USER_ID" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("USER_ID")
);

-- CreateTable
CREATE TABLE "Product" (
    "PRODUCT_ID" TEXT NOT NULL,
    "BUYER_ID" TEXT NOT NULL,
    "BUYER_FIRST_NAME" TEXT NOT NULL,
    "BUYER_LAST_NAME" TEXT NOT NULL,
    "BUYER_EMAIL_ID" TEXT NOT NULL,
    "BUYER_PHONE_NUMBER" TEXT NOT NULL,
    "PRODUCT_NAME" TEXT NOT NULL,
    "PRODUCT_TYPE" TEXT NOT NULL,
    "PRODUCT_PURCHASE_DATE" TEXT NOT NULL,
    "PRODUCT_SERIAL_NUMBER" TEXT NOT NULL,
    "PRODUCT_BRAND" TEXT NOT NULL,
    "WARRANTY_DURATION" TEXT NOT NULL,
    "WARRANTY_UNIT" TEXT NOT NULL,
    "WARRANTY_COVERAGE" TEXT NOT NULL,
    "WARRANTY_TYPE" TEXT NOT NULL,
    "BRAND_WARRANTY" TEXT NOT NULL,
    "VENDOR_NAME" TEXT NOT NULL,
    "VENDOR_RETURN_POLICY" TEXT NOT NULL,
    "PRODUCT_IMAGE_URL" TEXT NOT NULL,
    "PRODUCT_BILL_IMAGE_URL" TEXT NOT NULL,
    "WARRANTY_CARD_IMAGE_URL" TEXT NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("PRODUCT_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_EMAIL_key" ON "User"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "User_PASSWORD_key" ON "User"("PASSWORD");

-- CreateIndex
CREATE UNIQUE INDEX "Product_PRODUCT_SERIAL_NUMBER_key" ON "Product"("PRODUCT_SERIAL_NUMBER");

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_BUYER_ID_fkey" FOREIGN KEY ("BUYER_ID") REFERENCES "User"("USER_ID") ON DELETE CASCADE ON UPDATE CASCADE;
